# FastAPI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: rental_mania-fastapi:latest
        ports:
        - containerPort: 8000

---
# FastAPI Service
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# React Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: rental_mania-react:latest
        ports:
        - containerPort: 3000
        env:
          - name: CHOKIDAR_USEPOLLING
            value: "true"

---
# React Service
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
